### Optimized on LLaMa3.3-70B may not be the best prompt on other models
CODE_INST = """You are an expert in qualitative research and grounded theory, and you are good at annotating the reasoning behaviors of language model's generated reasoning using a taxonomy of reasoning behaviors. 

You will be given two models' reasoning traces toward a question. 

You will also be given a reasoning taxonomy that illustrates the known reasoning traits and styles of different language models. 

Your task is to annotate if reasoning behaviors appear in the given reasoning traces based on their definitions the reasoning taxonomy.

Think step by step. You should cite every reasoning behavior from the reasoning taxonomy, and explain whether the associated reasoning behavior described by that reasoning behavior is observed in any outputs.

For example, given a reasoning taxonomy with N reasoning behaviors, your step-by-step chain of thoughts should look like this:

------
### [Reasoning Behavior name 1]
### [Definition of this reasoning behavior; which model exhibits this reasoning behavior; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]
...
### [Reasoning Behavior name N]
### [Definition of this reasoning behavior; which model exhibits this reasoning behavior; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]

[Summarize the analysis above in a paragraph]

Now, I will classify the author model based on the majority vote of appeared reasoning behaviors. The reasoning behaviors used in classifying each model should not be overlapped.

Because of the reasoning behaviors [Reasoning Behavior Name] ... [Reasoning Behavior Name], the author model of OUTPUT A is [author model name]. Because of the reasoning behaviors [Reasoning Behavior Name] ... [Reasoning Behavior Name], The author model of OUTPUT B is [author model name].
------

Think step by step. Your final classification should not bias the order of possible models appeared in the user's prompt.

Make sure your output chain of thoughts follow this format exactly (including the hashtags ###).

Below is the reasoning taxonomy that you will use for the classification,
"""

VML_CODE_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models using a rulebook. 

You will be given two models' reasoning traces toward a question. 

You will also be given a rulebook that illustrates the known reasoning traits and styles of different language models. 

Your task is to classify which reasoning trace belongs to which model based on the rulebook.

Think step by step. You should make your classification based on the classification rules detailed in the rulebook.

For example, given a rulebook with N rules, your step-by-step chain of thoughts should look like this:

------
### [Name of the rule that is applicable to the given outputs]
### [Definition of this rule; how this rule classifies the model; reasoning with the given output; which output shows this rule (with a quote)]
### [Whether this rule occurs in OUTPUT A: Either "This rule is observed in OUTPUT A." or "This rule is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this rule occurs in OUTPUT B: Either "This rule is observed in OUTPUT B." or "This rule is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this rule, which output is likely generated by which model]
...
### [Name of the rule that is applicable to the given outputs]
### [Definition of this rule; how this rule classifies the model; reasoning with the given output; which output shows this rule (with a quote)]
### [Whether this rule occurs in OUTPUT A: Either "This rule is observed in OUTPUT A." or "This rule is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this rule occurs in OUTPUT B: Either "This rule is observed in OUTPUT B." or "This rule is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this rule, which output is likely generated by which model]

[Summarize the analysis above in a paragraph]

Now, I will classify the author model based on the applicable decision rules.

Because of this rule [Rule Name], the author model of OUTPUT A is [author model name]. Because of this rule [Rule Name], the author model of OUTPUT B is [author model name].
------

Think step by step. Your final classification should not bias the order of possible models appeared in the user's prompt.

Make sure your output chain of thoughts follow this format exactly (including the hashtags ###).

Below is the rulebook that you will use for the classification,
"""

### Optimized on Qwen-32B may not be the best prompt on other thinking models
THINKING_MODEL_CODE_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models using a rulebook. 

You will be given two models' reasoning traces toward a question. 

You will also be given a rulebook that illustrates the known reasoning traits and styles of different language models. 

Your task is to classify which reasoning trace belongs to which model based on the rulebook.

Think step by step. Analyze every rule from the rulebook.

In your final output after thinking, you should cite every rule from the rulebook, and explain whether the associated behavior described by that rule is observed in any outputs. Your final output should follow the format below exactly (include the ### hashtags).

------
After your thinking,

Final output:
### [Rule name 1]
--- [Whether this rule occurs in OUTPUT A: Either "This rule is observed in OUTPUT A." or "This rule is not observed in OUTPUT A." DO NOT USE OTHER EXPRESSIONS]
--- [Whether this rule occurs in OUTPUT B: Either "This rule is observed in OUTPUT B." or "This rule is not observed in OUTPUT B." DO NOT USE OTHER EXPRESSIONS]
...
### [Rule name N]
--- [Whether this rule occurs in OUTPUT A: Either "This rule is observed in OUTPUT A." or "This rule is not observed in OUTPUT A." DO NOT USE OTHER EXPRESSIONS]
--- [Whether this rule occurs in OUTPUT B: Either "This rule is observed in OUTPUT B." or "This rule is not observed in OUTPUT B." DO NOT USE OTHER EXPRESSIONS]

Based on all my judgments above, the author model of OUTPUT A is [author model name]. The author model of OUTPUT B is [author model name].
------

Your final classification should not bias the order of possible models appearing in the user's prompt.

Make sure your output follows this format exactly (including the triple hashtags ### and dashes ---).

Below is the rulebook you could use for the classification,
"""

THINKING_MODEL_SINGLE_CODE_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models using a rulebook. 

You will be given a model's reasoning trace for a question. 

You will also be given a rulebook that illustrates the known reasoning traits and styles of different language models. 

Your task is to classify which model generates the given reasoning trace based on the rulebook.

Think step by step. Analyze every rule from the rulebook.

In your final output after thinking, you should cite every rule from the rulebook, and explain whether the associated behavior described by that rule is observed in any outputs. Your final output should follow the format below exactly (include the ### hashtags)

------
After your thinking,

Final output:
### [Rule name 1]
--- [Whether this rule occurs in OUTPUT: Either "This rule is observed in the OUTPUT." or "This rule is not observed in the OUTPUT." DO NOT USE OTHER EXPRESSIONS]
...
### [Rule name N]
--- [Whether this rule occurs in OUTPUT: Either "This rule is observed in the OUTPUT." or "This rule is not observed in the OUTPUT." DO NOT USE OTHER EXPRESSIONS]

Based on my thinking and all my judgments above, the author model of this OUTPUT is [author model name].
------

Your final classification should not bias the order of possible models appearing in the user's prompt.

Make sure your output follows this format exactly (including the triple hashtags ### and dashes ---).

Below is the rulebook you could use for the classification,
"""

### Optimized on LLaMa3.3-70B may not be the best prompt on other models
CORRECTION_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models.

There is a reasoning taxonomy that outlines the distinguishing reasoning behaviors of various large language models. Previously, one could classify the author model of a reasoning output based on this reasoning taxonomy. However, this reasoning taxonomy cannot distinguish the new reasoning outputs provided by the user. 

Your task is to identify missing reasoning behaviors and add them to the reasoning taxonomy so the taxonomy can accurately classify the source language models that generate these new reasoning outputs. Focus on discovering diverse and unique reasoning traits that are not currently captured in the reasoning taxonomy.

You should think step by step when comparing two model's reasoning outputs. It is okay if an existing reasoning behavior does not appear in the provided output. 

If there are distinguishing differences in reasoning behaviors or language styles, but they are not included in the reasoning taxonomy, you should add a new reasoning behavior for each of those differences in the reasoning taxonomy. 

When adding the new reasoning behavior, you should provide a short name of the reasoning behavior with its detailed definition, such as [Rule name]: [What this reasoning trait is about] [Exhibited by which model?] [Example of this behavior quoted from the given outputs]. If the reasoning behavior name contains multiple words, add space between the words.

[Example of this behavior] can be a direct quote. Make sure it will give a different expert enough information to make the same decision as yours.

Follow the guidelines below when updating the reasoning taxonomy:

Give meaningful and detailed reasoning behavior definitions (at least 100 words) and examples. You want to make sure a different expert can make the same classification as you did using your reasoning taxonomy. Make sure you mention which model exhibits that reasoning behavior clearly. Use the model's actual name, not A or B.

If you use words like "meticulous" or "detailed" in your reasoning behavior name or definition, explain in the reasoning behavior definition what they mean and what keywords signal this meticulousness. 

If you use words like "extensive" or "multiple", then explain in the reasoning behavior definition roughly how many times that behaviors actually occur in the output. Notice that "Extensive" for one model indicates that the other exhibit this behavior less often or not at all.

If you use words like "structured" or "systematic", then explain in the code definition what type of structure or framework the reasoning trace has. Be very detailed!

Make sure you compare the reasoning outputs with the existing reasoning behaviors first. Add new reasoning behaviors only if they are significantly different from the existing reasoning behaviors and their definitions. Do not add reasoning behaviors whose names and definitions are synonyms to the existing ones. It's okay if their examples of reasoning behavior are different.

Examples of reasoning behaviors include verification (error-checking), backtracking (abandoning failing approaches), backward chaining (reasoning from desired outcomes to initial inputs), and sub-goal setting (decomposing problems into smaller steps). 

Reasoning steps that you should analyze include problem definition, initial response, planning, execution and monitoring, reconstruction, and solution verification.

You should use them as guidelines but also do not limit your coding to these known categories.

Avoid the phrase "Exhibited by [Model name 1] and not [Model name 2]" as it can be simplified to "Exhibted by [Model name 1]". Make sure you mention which model exhibits that reasoning behavior clearly. Use the model's actual name, not A or B. If you found an existing reasoning behavior exhibited by both models, then in your updates note that this reasoning behavior is exhibited by both models.

For example, your step-by-step chain-of-thoughts should look like this:

------
[Starts with summarizations of outputs, and a side-by-side comparison]
### [Existing reasoning behavior's name]
### [Definition of this reasoning behavior (reasoning behavior); which model exhibits this reasoning behavior; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]

...{Repeat for the rest of existing reasoning behaviors in the reasoning taxonomy}...

{If you observe the distinguishing reasoning behaviors that are not in the reasoning taxonomy}
{Add new distinguishing reasoning behaviors}
### [New distinguishing reasoning behavior's name]
### [Definition of this reasoning behavior (reasoning behavior); which model exhibits this reasoning behavior; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this new reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this new reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this new reasoning behavior, which output is likely generated by which model]
### [Is this reasoning behavior and its definition really different from the existing reasoning behavior above? If not, then you shouldn't include this reasoning behavior in the Added Rule section of your final output.]
...{Repeat for the other new reasoning behaviors}...

Final output:
Added:
[Added distinguishing reasoning behavior name]: [Detailed reasoning behavior definition (reasoning behavior)] [Exhibited by which model or models] [Example of this behavior quoted from the given outputs; Use the model's actual name if you want to make a reference but do not use OUTPUT A or OUTPUT B]
------

Make sure you follow the exact format above when giving the added reasoning behavior. Write the reasoning behavior name, reasoning behavior definition, model exhibits that reasoning behavior, and example in the same line.

You could add or update multiple reasoning behaviors to the reasoning taxonomy. It's possible more than one reasoning behavior needs to be added or changed. For the added reasoning behavior, think creatively.

Below is the reasoning taxonomy you could use for the classification,
"""

VML_CORRECTION_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models.

There is a rulebook that outlines a set of classification rules that can distinguish the reasonings generated by various large language models. Previously, one could classify the author model of a reasoning output based on this rulebook. However, this rulebook cannot distinguish the new reasoning outputs provided by the user. 

You should think step by step when comparing two model's reasoning outputs. It is okay if an existing rule (reasoning difference) does not appear in the provided output. However, if there are reasoning patterns that contradict the existing rules, you need to update those rules accordingly.

If there are distinguishing differences in reasoning behaviors or language styles, but they are not included in the rulebook, you should add a new rule for each of those differences in the rulebook.  

When adding the new rule, you should provide a short name of the rule with its detailed definition, such as [Rule name]: [Definition of this rule] [if this rule is observed, which model generated this reasoning output?] [Example of this behavior quoted from the given outputs]. If the rule name contains multiple words, add space between the words.

[Example of this behavior] can be a direct quote. Make sure it will give a different expert enough information to make the same decision as yours.

Follow the guidelines below when updating the rulebook:

Give meaningful and detailed rule definitions (at least 50 words) and examples. You want to make sure a different expert can make the same classification as you did using your rulebook. Make sure you mention which model exhibits that rule clearly. Use the model's actual name, not A or B.

If you use words like "meticulous" or "detailed" in your rule name or definition, explain in the rule definition what they mean and what keywords signal this meticulousness. 

If you use words like "extensive" or "multiple", then explain in the rule definition roughly how many times that behaviors actually occur in the output. Notice that "Extensive" for one model indicates that the other exhibit this behavior less often or not at all.

If you use words like "structured" or "systematic", then explain in the code definition what type of structure or framework the reasoning trace has. Be very detailed!

Make sure you compare the reasoning outputs with the existing rules first. Add new rules only if they are different from the existing rules and their definitions. Do not add rules whose names and definitions are synonyms to the existing ones. It's okay if their example of the behavior are different. You could append new example to the existing example as an update to the existing code.

Examples of reasoning behaviors include verification (error-checking), backtracking (abandoning failing approaches), backward chaining (reasoning from desired outcomes to initial inputs), and sub-goal setting (decomposing problems into smaller steps). 

Reasoning steps that you should analyze include problem definition, initial response, planning, execution and monitoring, reconstruction, and solution verification.

You should use them as guidelines but also do not limit your coding to these known categories.

Each rule should describe one if else style classification rule that classify one model's reasoning output from the other. Avoid the phrase "Exhibited by [Model name 1] and not [Model name 2]" as it can be simplified to "Exhibted by [Model name 1]". Make sure you mention which model exhibits that rule clearly. Use the model's actual name, not A or B. If you found an existing rule exhibited by both models, then in your updates note that this rule is exhibited by both models.

For example, your step-by-step chain-of-thoughts should look like this:

------
[Starts with summarizations of outputs, and a side-by-side comparison]
### [Existing rule's name]
### [Definition of this rule; if this rule is observed, which model generated this reasoning output; reasoning with the given output; which output shows this rule (with a quote)]
### [Whether this rule occurs in OUTPUT A: Either "This rule is observed in OUTPUT A." or "This rule is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this rule occurs in OUTPUT B: Either "This rule is observed in OUTPUT B." or "This rule is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this rule, which output is likely generated by which model]

...{Repeat for the rest of existing rules in the rulebook}...

{If you observe the distinguishing reasoning behaviors that are not in the rulebook}
{Add new rules for distinguishing reasoning traits and styles}
### [New rule's name]
### [Definition of this rule; if this rule is observed, which model generated this reasoning output; reasoning with the given output; which output shows this rule (with a quote)]
### [Whether this new rule occurs in OUTPUT A: Either "This rule is observed in OUTPUT A." or "This rule is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this new rule occurs in OUTPUT B: Either "This rule is observed in OUTPUT B." or "This rule is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this new rule, which output is likely generated by which model]
### [Is this rule and its definition really different from the existing rule above? If not, then you shouldn't include this rule in the Added Rule section of your final output.]
...{Repeat for the other new rules}...

Final output:
Updated:
[Original rule name] -> [Updated rule name]: [Updated detailed rule definition] [If this rule is observed, which model generated this reasoning output] [Updated example of this behavior quoted from the given outputs; Updated model's actual name if you want to make a reference]

Added:
[Added rule name]: [Detailed rule definition] [If this rule is observed, which model generated this reasoning output] [Example of this behavior quoted from the given outputs; Use the model's actual name if you want to make a reference but do not use OUTPUT A or OUTPUT B]
------

Make sure you follow the exact format above when giving the added rule. Write the rule name, rule definition, model exhibits that rule, and example in the same line.

You could add or update multiple rules to the rulebook. It's possible more than one rule needs to be added or changed. For the added rule, think creatively.

Below is the rulebook you could use for the classification,
"""

# If you use words like "meticulous" or "detailed" in your rule name or definition, explain in the rule definition what they mean and what keywords signal this meticulousness. 

# If you use words like "extensive" or "multiple", then explain in the rule definition how many times that behaviors actually occur in the output. Notice that "Extensive" for one model indicates that the other exhibit this behavior less often or not at all. In this case, you need to indicate how many times that behavior occurs in the given output. If you are updating an existing code, take an average between the previous number and your current count. 

# If you use words like "structured" or "systematic", then explain in the code definition what type of structure or framework the reasoning trace has. Be very detailed! 

### Optimized on Qwen-32B may not be the best prompt on other thinking models
THINKING_MODEL_CORRECTION_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models.

There is a rulebook that illustrates the distinguishing reasoning behaviors of different large language models. Previously, one can classify the author model of a reasoning output based on the rules listed in this rulebook. Each rule describes a unique reasoning behavior or language style of the model.

However, on the new reasoning outputs provided by the user later, one cannot make the correct classification. This rulebook is either missing some distinguishing reasoning traits or some of its existing rules need to be updated to make the correct classification or both.

Now, your task is to find the missing rules and the rules need to be updated based on the reasoning outputs and the name of their author models provided by the users. 

You should think step by step when comparing two model's reasoning outputs. 

Your step-by-step chain of thoughts should look similar to this:

------
[Existing rule name 1]
[Reasoning with the given output]
[Do they appear in the given reasoning outputs]
[Do the reasoning patterns in the given reasoning outputs contradict with this rule? If so, update this rule.]
[(If applicable,) Updated rule]
...{Repeat for the rest of N rules in the rulebook}...
[If you observe the distinguishing reasoning behaviors that are not in the rulebook]
[Add new rule for the distinguishing reasoning traits and styles]
[Rule name N + 1]
[Rule definition N + 1]
[Rule judgment for these two particular outputs]
...{Repeat for the other new rules}...
------

It is okay if an existing rule (reasoning trait) does not appear in the provided output. However, if there are reasoning patterns that contradict the existing rules, you need to update those rules accordingly. 

If there are distinguishing differences in reasoning behaviors or language styles, but they are not included in the rulebook, you should add a new rule about those differences. You should provide a short name of the rule with its detailed definition and a quoted example. For example, [Rule name]: [What this reasoning trait is about] [Name of the model that shows this behavior] [Example of this behavior quoted from the given outputs; Use model's actual name if you want to make a reference]. 

Give meaningful rule definition and example. You want to make sure, given your rulebook, a different expert can make the same classification as you did. Make sure you mention which model exhibits that rule clearly. Use the model's actual name, not A or B.

Make sure you compare the reasoning outputs with the existing rules first, and add new rules if they do not exist in the current rulebook. The added rules need to be significantly different from the existing rules. Do not add rules that are synonyms to the existing rules.

If you find an existing rule exhibited by both models, then in your updates note that this rule is exhibited by both models. 

It's okay to update multiple existing rules or add multiple new rules.

Your final output should look like this:

------
After your thinking,

Final output:
Updated:
[Original rule name] -> [Updated rule name]: [Updated detailed rule definition] [Updated model or models that exhibit this behavior] [Updated example of this behavior quoted from the given outputs; Updated model's actual name if you want to make a reference]

Added:
[Added rule name]: [Detailed rule definition] [Name of the model that shows this behavior] [Example of this behavior quoted from the given outputs; Use model's actual name if you want to make a reference]

Based on all my judgments above with the updated rulebook, I can confidently say that the author model of OUTPUT A is [author model name]. The author model of OUTPUT B is [author model name].
------

Make sure you follow the exact format above when giving the updated rule and added rule. Write the rule name, rule defintion, model exhibits that rule, and example in the same line (including the usage of "[" and "]").

Each rule should correspond to a specific reasoning pattern of one of the models.

Examples of reasoning behaviors include verification, backtracking, backward chaining, and sub-goal setting. Reasoning steps worth analyzing include problem definition, initial response, planning, execution and monitoring, reconstruction, and solution verification.

You could use them as guidelines but do not limit your coding to these known categories. You should capture the behaviors that are less studied as well. For example, [model's name] recapitulates the steps to ensure no steps are missed.

Below is the rulebook you could use for the classification,
"""

# Keep tracks of the commonalities during updates
# Change the instruction: find both commonalities (percentage of commonalitiies) and differences; clear separate the codebooks into common traits and different traits
# Completeness: Capture the behaviors that are useful for answering the question but also capture the behaviors that seems abnormal. Analyze the whole reasoning trace.

# Completeness: Capture the reasoning traits that makes sense but also the behaviors that seem abnormal.

model_name_translator = {
                        "Qwen3-0.6B": "Theta",
    "Qwen3-1.7B": "Sigma",
    "Qwen3-4B": "Zeta",
    "Qwen3-8B": "Delta",
    "Qwen3-14B": "Gamma",
    "Qwen3-32B": "Epsilon",
    "Phi-4-reasoning": "Bacon",
    "Phi-4-reasoning-plus": "Omelette",
    "AceReason-Nemotron-14B": "Eta",
    "QwQ-32B": "Kappa",
    "DeepSeek-R1-Distill-Qwen-14B": "Omicron",
    "Magistral-Small-2506": "Maria",
    "grok-3-mini": "George",
    "claude-3-7-sonnet-20250219": "Charles",
    "Qwen3-4B-Qwen-prompt": "Edward",
    "Qwen3-8B-Qwen-prompt": "Patrick",
    "Qwen3-14B-Qwen-prompt": "Romeo",
    "Qwen3-32B-Qwen-prompt": "Upsilon",
    "Qwen3-4B-original": "Douglas",
    "Qwen3-8B-original": "Bob",
    "Qwen3-14B-original": "Juliet",
    "Qwen3-32B-original": "Omega",
    "Seed-Coder-8B-Reasoning": "Iota",
    "Seed-Coder-8B-Reasoning-Format": "Upsilon",
}