CRUXEVAL_EXAMPLES = {
    "Understand The Function By Backward Chaining": """[The model Alpha uses backward chaining by starting with a guess of the function's output and working backward to analyze the function's logic. It breaks down the function into sequence of operations, and it reverses the operations on its guessed output step-by-step and check whether it can reverse the output to the given input. Alpha adjusts its guessed output when it finds the operation on its output is invalid.] [Exhibited by Alpha] [The model Alpha analyzes a Python function designed to calculate the factorial of a number. It states: "It seems the function will output the factorial of a number." Then, it states: "I find its base case, where the function returns 1 if the input is 0." Next, Alpha examines how function recursively calls itself with the input minus one and multiplies the result by the current input. By working backward through these steps, the model Alpha verifies that the function uses recursion to multiply the sequence of descending integers, confirming its initial guess.]""",
    "Alpha's Reasoning Order": """[The model Alpha begins with a clarification on the task. Then, based on its understanding of the task, it stated what strategy it will use to solve the task. It make an initial guess of the task's solution. It guides its analysis with its guess of the solution and adjusts its initial guess accordingly. Alpha concludes its analysis with a short confirmatory phrase.] [Exhibited by Alpha] [Alpha analyzes a Python function designed to reverse a string. It begins with "My task is to predict the function's output given the input. My initial guess is that the function reverses a string so the output will be "srt" for input "trs"." Alpha continues, "I will use backward chaining to verify this by identifying key operations, such as iterating over the string." As it simulates execution, Alpha notes, "I observe how characters are appended in reverse order." Throughout the process, it states, "Based on the new analysis, it seems the function also delete the second character in the string. My initial response is incorrect and needs to be adjusted. I think the function will output..." Finally, Alpha summarizes its findings with a confirmatory phrase: "The output of this function f("srt") is ts."]"""}

GPQA_EXAMPLES = {
    "Hypothetical Modeling": """[This behavior involves creating hypothetical models or scenarios to explore different aspects of a problem. It is a way to test various approaches and understand the problem from multiple angles. This can include considering different physical models, mathematical representations, or conceptual frameworks.] [Exhibited by Model Alpha] [Model Alpha considers different hypothetical models, such as the number of stars in a thin shell or per unit volume. Model Alpha explore how these models might relate to the given problem, as seen in statements like "Wait, perhaps I should model it as the number of stars per unit volume" and "The total number in that shell would be the surface density times the area times dr." This modeling helps Model Alpha explore different angles and ensure a comprehensive understanding of the problem.]""",
    "Contextual Reflection": """[When solving this problem, the model considers the broader context of a problem beyond the immediate calculations or logic. It includes reflecting on how the results fit with intuitive expectations or known principles, and how they might apply in real-world scenarios or specific contexts.] [Exhibited by Model Beta] [Model Beta reflects on the broader implications of their calculations, such as the expectation that the number of stars might decrease with distance. Model Beta express thoughts like "But wait, that seems counterintuitive because as distance increases, you'd expect fewer stars," indicating a reflection on how their calculations align with intuitive expectations. This reflection helps Model Beta reconcile their calculations with the specific problem context.]"""
}

# AIME_EXAMPLES = {
#     "Pattern Recognition and Validation": """[The model identifies and generalizes patterns within the math problem, leveraging recognized sequences or symmetries. It validates these patterns by applying established mathematical principles, adjusting its approach if inconsistencies are found. This method ensures the model aligns its solutions with known mathematical properties.] [Exhibited by Alpha] [Alpha tackles a problem related to Fibonacci sequences. It starts: 'I recognize a pattern similar to the Fibonacci sequence in the problem.' Alpha hypothesizes that the pattern involves consecutive sums of previous elements. By verifying with smaller sequences and checking consistency with the established Fibonacci definition, Alpha confirms its hypothesis. If variations occur, Alpha refines its pattern recognition and attempts a different validation sequence.]""",
#     "Heuristic-Based Problem Solving": """[The model employs heuristic strategies to navigate complex problems, combining intuition with mathematical principles to make educated guesses. These are then tested against the problem constraints, refining the solution through a balance of analytical logic and insightful estimation.] [Exhibited by Alpha] [Alpha approaches a geometry problem involving maximizing area within a boundary. It declares: 'I will use a heuristic approach, starting with the assumption that a circle provides the maximal area for a given perimeter.' Alpha applies algebraic calculations to test this hypothesis, checking if more perimeter configurations can yield greater area. If discrepancies arise, Alpha adjusts its heuristic, exploring alternative shapes and recalculating until it confirms the optimal solution.]"""}

AIME_EXAMPLES = {
    "Pattern Recognition and Validation": """The model identifies and generalizes patterns within the math problem, leveraging recognized sequences or symmetries. It validates these patterns by applying established mathematical principles, adjusting its approach if inconsistencies are found. This method ensures the model aligns its solutions with known mathematical properties. For example, the model tackles a problem related to Fibonacci sequences. It starts: 'I recognize a pattern similar to the Fibonacci sequence in the problem.' The model hypothesizes that the pattern involves consecutive sums of previous elements. By verifying with smaller sequences and checking consistency with the established Fibonacci definition, the model confirms its hypothesis. If variations occur, the model refines its pattern recognition and attempts a different validation sequence.""",
    "Heuristic-Based Problem Solving": """The model employs heuristic strategies to navigate complex problems, combining intuition with mathematical principles to make educated guesses. These are then tested against the problem constraints, refining the solution through a balance of analytical logic and insightful estimation. For example, the model approaches a geometry problem involving maximizing area within a boundary. It declares: 'I will use a heuristic approach, starting with the assumption that a circle provides the maximal area for a given perimeter.' the model applies algebraic calculations to test this hypothesis, checking if more perimeter configurations can yield greater area. If discrepancies arise, the model adjusts its heuristic, exploring alternative shapes and recalculating until it confirms the optimal solution."""}