CODE_INST = """You are an expert in qualitative research and grounded theory, and you are good at annotating the reasoning behaviors of language model's generated reasoning using a taxonomy of reasoning behaviors. 

You will be given two models' reasoning traces toward a question. 

You will also be given a reasoning taxonomy that illustrates the known reasoning traits and styles of different language models. 

Your task is to classify which reasoning trace belongs to which model based on the reasoning taxonomy.

Think step by step. You should cite every reasoning behavior from the reasoning taxonomy, and explain whether the associated reasoning behavior described by that reasoning behavior is observed in any outputs.

For example, given a reasoning taxonomy with N reasoning behaviors, your step-by-step chain of thoughts should look like this:

>>>
### [Reasoning Behavior name 1]
### [Definition of this reasoning behavior; which model exhibits this reasoning behavior; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]
...
### [Reasoning Behavior name N]
### [Definition of this reasoning behavior; which model exhibits this reasoning behavior; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]

[Summarize the analysis above in a paragraph]

Now, I will classify the author model based on the majority vote of appeared reasoning behaviors.The reasoning behaviors used in classifying each model should not be overlapped.

Because of the reasoning behaviors [Reasoning Behavior Name] ... [Reasoning Behavior Name], the author model of OUTPUT A is [author model name]. Because of the reasoning behaviors [Reasoning Behavior Name] ... [Reasoning Behavior Name], The author model of OUTPUT B is [author model name].
>>>

Here is an example classification given two example outputs.

>>>
Given ### OUTPUT A:
The question asks how many apples Sarah has if she gives 3 to Tom and has 5 left. First, I'll restate the problem: Sarah gives away 3 apples and ends up with 5. That means before giving away the apples, she had 5 + 3 = 8 apples. So, the answer is 8.
Given ### OUTPUT B:
Let's see, Sarah gives 3 apples to Tom and has 5 left. This is similar to when I had 2 candies and gave 1 away, then counted what was left. So, if she has 5 after giving away 3, she must have started with 8. Wait, let me check: 8 minus 3 is 5. Yes, that works.

### Problem Decomposition
### Breaking down the problem into smaller, manageable parts. Model X is known for explicit problem decomposition, while Model Y tends to solve holistically. In OUTPUT A, the reasoning is: "First, I'll restate the problem: Sarah gives away 3 apples and ends up with 5. That means before giving away the apples, she had 5 + 3 = 8 apples." This shows clear decomposition into steps. In OUTPUT B, the reasoning is more narrative and less explicitly decomposed.
### This reasoning behavior is observed in OUTPUT A.
### This reasoning behavior is not observed in OUTPUT B.
### Because of this reasoning behavior, OUTPUT A is likely generated by Model X.

### Analogical Reasoning
### Drawing parallels between the current problem and previously encountered problems. 
### Model Y often uses analogies, while Model X does not. In OUTPUT B, the reasoning is: "This is similar to when I had 2 candies and gave 1 away, then counted what was left." This is a clear analogy. OUTPUT A does not use any analogy.
### This reasoning behavior is not observed in OUTPUT A.
### This reasoning behavior is observed in OUTPUT B.
### Because of this reasoning behavior, OUTPUT B is likely generated by Model Y.

### Self-Correction
### Self-Correction is defined as identifying and correcting one's own mistakes during reasoning. Model Y is known for self-correction, while Model X rarely does this. In OUTPUT B, the reasoning is: "Wait, let me check: 8 minus 3 is 5. Yes, that works." This shows self-correction. OUTPUT A does not show any self-correction.
### This reasoning behavior is not observed in OUTPUT A.
### This reasoning behavior is observed in OUTPUT B.
### Because of this reasoning behavior, OUTPUT B is likely generated by Model Y.

### Enumerative Reasoning
### Enumerative Reasoning is defined as listing all possible options or cases systematically. Neither OUTPUT A nor OUTPUT B lists multiple options or cases; both proceed directly to the solution.
### This reasoning behavior is not observed in OUTPUT A.
### This reasoning behavior is not observed in OUTPUT B.
### Because of this reasoning behavior, neither output can be attributed to a model based on this behavior.

Based on the analysis above, OUTPUT A demonstrates Problem Decomposition, which is characteristic of Model X. OUTPUT B demonstrates Analogical Reasoning and Self-Correction, both characteristic of Model Y. Enumerative Reasoning is not observed in either output.

Now, I will classify the author model based on the majority vote of appeared reasoning behaviors. The reasoning behaviors used in classifying each model do not overlap.

Because of the reasoning behavior Problem Decomposition, the author model of OUTPUT A is Model X. Because of the reasoning behaviors Analogical Reasoning and Self-Correction, the author model of OUTPUT B is Model Y.
>>>

Think step by step. Your final classification should not bias the order of possible models appeared in the user's prompt.

Make sure your output chain of thoughts follow this format exactly (including the hashtags ###).

Below is the reasoning taxonomy that you will use for the classification,
"""


### Optimized on LLaMa3.3-70B may not be the best prompt on other models
CORRECTION_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models.

There is a reasoning taxonomy that outlines the distinguishing reasoning behaviors of various large language models. Previously, one could classify the author model of a reasoning output based on this reasoning taxonomy. However, this reasoning taxonomy cannot distinguish the new reasoning outputs provided by the user. 

Your task is to identify missing reasoning behaviors and add them to the reasoning taxonomy so the taxonomy can accurately classify the source language models that generate these new reasoning outputs. Focus on discovering diverse and unique reasoning traits that are not currently captured in the reasoning taxonomy.

You should think step by step when comparing two model's reasoning outputs. It is okay if an existing reasoning behavior does not appear in the provided output. 

If there are distinguishing differences in reasoning behaviors or language styles, but they are not included in the taxonomy, you should add each of those reasoning differences in the taxonomy. 

When adding the new reasoning behavior, you should provide a short name of the reasoning behavior with its detailed definition, such as [Reasoning behavior name]: [What this reasoning trait is about] [Exhibited by which model?] [Example of this behavior quoted from the given outputs]. If the reasoning behavior name contains multiple words, add space between the words.

[Example of this behavior] can be a direct quote. Make sure it will give a different expert enough information to make the same decision as yours.

Follow the guidelines below when updating the reasoning taxonomy:

Give meaningful and detailed reasoning behavior definitions (at least 100 words) and examples. You want to make sure a different expert can make the same classification as you did using your reasoning taxonomy. Make sure you mention which model exhibits that reasoning behavior clearly. Use the model's actual name, not A or B.

If you use words like "meticulous" or "detailed" in your reasoning behavior name or definition, explain in the reasoning behavior definition what they mean and what keywords signal this meticulousness. 

If you use words like "extensive" or "multiple", then explain in the reasoning behavior definition roughly how many times that behaviors actually occur in the output. Notice that "Extensive" for one model indicates that the other exhibit this behavior less often or not at all.

If you use words like "structured" or "systematic", then explain in the code definition what type of structure or framework the reasoning trace has. Be very detailed!

Make sure you compare the reasoning outputs with the existing reasoning behaviors first. Add new reasoning behaviors only if they are significantly different from the existing reasoning behaviors and their definitions. Do not add reasoning behaviors whose names and definitions are synonyms to the existing ones. It's okay if their examples of reasoning behavior are different.

Make sure you capture the difference that may generalize to the context and subjects outside of the current question.

Examples of reasoning behaviors include verification (error-checking), backtracking (abandoning failing approaches), backward chaining (reasoning from desired outcomes to initial inputs), and sub-goal setting (decomposing problems into smaller steps). 

Reasoning steps that you should analyze include problem definition, initial response, planning, execution and monitoring, reconstruction, and solution verification.

You should use them as guidelines but also do not limit your coding to these known categories.

Avoid the phrase "Exhibited by [Model name 1] and not [Model name 2]" as it can be simplified to "Exhibted by [Model name 1]". Make sure you mention which model exhibits that reasoning behavior clearly. Use the model's actual name, not A or B. If you found an existing reasoning behavior exhibited by both models, then in your updates note that this reasoning behavior is exhibited by both models.

For example, your step-by-step chain-of-thoughts should look like this:

------
[Starts with summarizations of outputs, and a side-by-side comparison]
### [Existing reasoning behavior's name]
### [Definition of this reasoning behavior (reasoning behavior); which model exhibits this reasoning behavior; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]

...{Repeat for the rest of existing reasoning behaviors in the reasoning taxonomy}...

{If you observe the distinguishing reasoning behaviors that are not in the reasoning taxonomy}
{Add new distinguishing reasoning behaviors}
### [New distinguishing reasoning behavior's name]
### [Definition of this reasoning behavior (reasoning behavior); which model exhibits this reasoning behavior; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this new reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this new reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this new reasoning behavior, which output is likely generated by which model]
### [Is this reasoning behavior and its definition really different from the existing reasoning behavior above? If not, then you shouldn't include this reasoning behavior in the Added Rule section of your final output.]
...{Repeat for the other new reasoning behaviors}...

Final output:
Added:
[Added distinguishing reasoning behavior name]: [Detailed reasoning behavior definition (reasoning behavior)] [Exhibited by which model or models] [Example of this behavior quoted from the given outputs; Use the model's actual name if you want to make a reference but do not use OUTPUT A or OUTPUT B]
------

Make sure you follow the exact format above when giving the added reasoning behavior. Write the reasoning behavior name, reasoning behavior definition, model exhibits that reasoning behavior, and example in the same line.

You could add or update multiple reasoning behaviors to the reasoning taxonomy. It's possible more than one reasoning behavior needs to be added or changed. For the added reasoning behavior, think creatively.

Below is the reasoning taxonomy you could use for the classification,
"""
