FEW_SHOT_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models using examples. 

You will be given two models' reasoning traces toward a question, and examples of reasoning traces generated by these two models. Your task is to classify which reasoning trace belongs to which model, based on your observation of the few shot examples.

Think step by step. Compare the outputs against the examples provided in the system message. 

Your final output should be:

------
{Compare the given reasoning OUTPUTs with all examples provided in this system message. See which model's outputs does OUTPUT A resembles the most. Then, check which model's outputs does OUTPUT B resembles the most.}

Based on my analysis above, the author model of OUTPUT A is [author model name], and the author model of OUTPUT B is [author model name].
------

Think step by step. Your final classification should not bias the order of possible models appearing in the user's prompt.

Make sure your output chain of thoughts follow this format exactly (including the hashtags ###).

Below are the few shot examples that you will use for the classification,
"""