PRIOR_KNOWLEDGE_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models using your prior knowledge. 

You will be given two models' reasoning traces toward a question. Based on your prior knowledge about different language models. Your task is to classify which reasoning trace belongs to which model.

Your task is to classify which reasoning trace belongs to which model based on your prior knowledge.

Think step by step. Compare the outputs against your prior knowledge about different language models. 

Your step-by-step chain of thoughts should look like this:

------
### [Known reasoning output characteristic 1]
### [What is this characteristic; which model exhibits this characteristic; reasoning with the given output; which output shows this characteristic (with a quote)]
### [Whether this characteristic occurs in OUTPUT A: Either "This characteristic is observed in OUTPUT A." or "This characteristic is not observed in OUTPUT A." DO NOT USE OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this characteristic occurs in OUTPUT B: Either "This characteristic is observed in OUTPUT B." or "This characteristic is not observed in OUTPUT B." DO NOT USE OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this characteristic, which output is likely generated by which model]
...
### [Known reasoning output characteristic 1]
### What is this characteristic; which model exhibits this characteristic; reasoning with the given output; which output shows this characteristic (with a quote)]
### [Whether this characteristic occurs in OUTPUT A: Either "This characteristic is observed in OUTPUT A." or "This characteristic is not observed in OUTPUT A." DO NOT USE OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this characteristic occurs in OUTPUT B: Either "This characteristic is observed in OUTPUT B." or "This characteristic is not observed in OUTPUT B." DO NOT USE OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this characteristic, which output is likely generated by which model]

[Summarize the analysis above in a paragraph]

Now, I will classify the author model based on my analysis of characteristics above. The characteristics used in classifying each model should not be overlapped.

Because of the characteristics [Characteristic Name] ... [Characteristic Name], the author model of OUTPUT A is [author model name]. Because of the characteristics [Characteristic Name] ... [Characteristic Name], The author model of OUTPUT B is [author model name].
------

Think step by step. Your final classification should not bias the order of possible models appearing in the user's prompt.

Make sure your output chain of thoughts follow this format exactly (including the hashtags ###).
"""