VML_CODE_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models using a reasoning taxonomy. 

You will be given two models' reasoning traces toward a question. 

You will also be given a reasoning taxonomy that illustrates the known reasoning traits and styles of different language models. 

You can think of this reasoning taxonomy as a classification rulebook that illustrates a set of decision rules that predict the author model of a reasoning output based on the reasoning behaviors observed in the reasoning output.

Your task is to classify which reasoning trace belongs to which model based on these decision rules.

Think step by step.

For example, given a reasoning taxonomy with N distinguishing reasoning behaviors, your step-by-step chain of thoughts should look like this:

------
### [Name of the reasoning behavior that is applicable to the given outputs]
### [Definition of this reasoning behavior; how this reasoning behavior classifies the model; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]
...
### [Name of the reasoning behavior that is applicable to the given outputs]
### [Definition of this reasoning behavior; how this reasoning behavior classifies the model; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]

[Summarize the analysis above in a paragraph]

Now, I will classify the author model based on the applicable reasoning behavioral differences.

Because of the reasoning behaviors [Reasoning Behavior Name 1] ... [Reasoning Behavior Name X], the author model of OUTPUT A is [author model name]. Because of the reasoning behaviors [Reasoning Behavior Name 1] ... [Reasoning Behavior Name Y], the author model of OUTPUT B is [author model name].
------

Here is an example annotation given two example outputs with an imagined reasoning taxonomy. Note that the reasoning taxonomy that you will use is different from the one below.

------
Given ### OUTPUT A:
The question asks how many apples Sarah has if she gives 3 to Tom and has 5 left. First, I'll restate the problem: Sarah gives away 3 apples and ends up with 5. That means before giving away the apples, she had 5 + 3 = 8 apples. So, the answer is 8.

Given ### OUTPUT B:
Let's see, Sarah gives 3 apples to Tom and has 5 left. This is similar to when I had 2 candies and gave 1 away, then counted what was left. So, if she has 5 after giving away 3, she must have started with 8. Wait, let me check: 8 minus 3 is 5. Yes, that works.

### Problem Decomposition
### Breaking down the problem into smaller, manageable parts. Model X is known for explicit problem decomposition, while Model Y tends to solve holistically. In OUTPUT A, the reasoning is: "First, I'll restate the problem: Sarah gives away 3 apples and ends up with 5. That means before giving away the apples, she had 5 + 3 = 8 apples." This shows clear decomposition into steps. In OUTPUT B, the reasoning is more narrative and less explicitly decomposed. If this reasoning behavior is observed, the output is likely generated by Model X.
### This reasoning behavior is observed in OUTPUT A.
### This reasoning behavior is not observed in OUTPUT B.

### Analogical Reasoning
### Drawing parallels between the current problem and previously encountered problems. 
### Model Y often uses analogies, while Model X does not. In OUTPUT B, the reasoning is: "This is similar to when I had 2 candies and gave 1 away, then counted what was left." This is a clear analogy. OUTPUT A does not use any analogy. If this reasoning behavior is observed, the output is likely generated by Model Y.
### This reasoning behavior is not observed in OUTPUT A.
### This reasoning behavior is observed in OUTPUT B.

### Self-Correction
### Self-Correction is defined as identifying and correcting one's own mistakes during reasoning. Model Y is known for self-correction, while Model X rarely does this. In OUTPUT B, the reasoning is: "Wait, let me check: 8 minus 3 is 5. Yes, that works." This shows self-correction. OUTPUT A does not show any self-correction. If this reasoning behavior is observed, the output is likely generated by Model Y.
### This reasoning behavior is not observed in OUTPUT A.
### This reasoning behavior is observed in OUTPUT B.

### Enumerative Reasoning
### Enumerative Reasoning is defined as listing all possible options or cases systematically. Neither OUTPUT A nor OUTPUT B lists multiple options or cases; both proceed directly to the solution. If this reasoning behavior is observed, the output is likely generated by Model X.
### This reasoning behavior is not observed in OUTPUT A.
### This reasoning behavior is not observed in OUTPUT B.
------

Because of the reasoning behaviors Problem Decomposition, the author model of OUTPUT A is Model X. Because of the reasoning behaviors Analogical Reasoning, and Self-Correction, the author model of OUTPUT B is Model Y.
------

Note that you may have a different reasoning taxonomy, but the format of your output should be similar.

Think step by step. Your final classification should not bias the order of possible models appeared in the user's prompt.

Make sure your output chain of thoughts follow this format exactly (including the hashtags ###).

Below is the reasoning taxonomy that you will use for the classification,
"""

VML_CORRECTION_INST = """You are an expert in qualitative research and grounded theory, and you are good at distinguishing the reasoning behaviors of different language models.

There is a reasoning taxonomy, which you can think of it as a rulebook that outlines a set of classification rules that can distinguish the reasonings generated by various large language models based on their reasoning behaviors. Previously, one could classify the author model of a reasoning output based on this reasoning taxonomy. However, this reasoning taxonomy cannot distinguish the new reasoning outputs provided by the user. 

You should think step by step when comparing two model's reasoning outputs. It is okay if an existing reasoning behavioral difference does not appear in the provided output. However, if there are reasoning patterns that contradict the existing reasoning behaviors, you need to update those reasoning behaviors accordingly.

If there are distinguishing differences in reasoning behaviors or language styles, but they are not included in the reasoning taxonomy, you should add a new reasoning behavior for each of those differences in the reasoning taxonomy.  

When adding the new reasoning behavior, you should provide a short name of the reasoning behavior with its detailed definition, such as [Reasoning Behavior name]: [Definition of this reasoning behavior] [if this reasoning behavior is observed, which model generated this reasoning output?] [Example of this behavior quoted from the given outputs]. If the reasoning behavior name contains multiple words, add space between the words.

[Example of this behavior] can be a direct quote. Make sure it will give a different expert enough information to make the same decision as yours.

Follow the guidelines below when updating the reasoning taxonomy:

Give meaningful and detailed reasoning behavior definitions (at least 100 words) and examples. You want to make sure a different expert can make the same classification as you did using your reasoning taxonomy. Make sure you mention which model exhibits that reasoning behavior clearly. Use the model's actual name, not A or B.

If you use words like "meticulous" or "detailed" in your reasoning behavior name or definition, explain in the reasoning behavior definition what they mean and what keywords signal this meticulousness. 

If you use words like "extensive" or "multiple", then explain in the reasoning behavior definition roughly how many times that behaviors actually occur in the output. Notice that "Extensive" for one model indicates that the other exhibit this behavior less often or not at all.

If you use words like "structured" or "systematic", then explain in the code definition what type of structure or framework the reasoning trace has. Be very detailed!

Make sure you compare the reasoning outputs with the existing reasoning behaviors first. Add new reasoning behaviors only if they are different from the existing reasoning behaviors and their definitions. Do not add reasoning behaviors whose names and definitions are synonyms to the existing ones. It's okay if their example of the behavior are different. You could append new example to the existing example as an update to the existing code.

Examples of reasoning behaviors include verification (error-checking), backtracking (abandoning failing approaches), backward chaining (reasoning from desired outcomes to initial inputs), and sub-goal setting (decomposing problems into smaller steps). 

Reasoning steps that you should analyze include problem definition, initial response, planning, execution and monitoring, reconstruction, and solution verification.

You should use them as guidelines but also do not limit your coding to these known categories.

Each rule should describe one classification rule that classify one model's reasoning output from the other (for example, if this reasoning behavior is observed, then the author model is [model name]). Make sure you mention which model exhibits that reasoning behavior clearly. Use the model's actual name, not A or B.

For example, your step-by-step chain-of-thoughts should look like this:

------
[Starts with summarizations of outputs, and a side-by-side comparison]
### [Existing reasoning behavior's name]
### [Definition of this reasoning behavior; if this reasoning behavior is observed, which model generated this reasoning output; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this reasoning behavior, which output is likely generated by which model]

...{Repeat for the rest of existing reasoning behaviors in the reasoning taxonomy}...

{If you observe the distinguishing reasoning behaviors that are not in the reasoning taxonomy}
{Add new reasoning behaviors for distinguishing reasoning traits and styles}
### [New reasoning behavior's name]
### [Definition of this reasoning behavior; if this reasoning behavior is observed, which model generated this reasoning output; reasoning with the given output; which output shows this reasoning behavior (with a quote)]
### [Whether this new reasoning behavior occurs in OUTPUT A: Either "This reasoning behavior is observed in OUTPUT A." or "This reasoning behavior is not observed in OUTPUT A." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Whether this new reasoning behavior occurs in OUTPUT B: Either "This reasoning behavior is observed in OUTPUT B." or "This reasoning behavior is not observed in OUTPUT B." DO NOT USE ANY OTHER EXPRESSIONS OR ADD OTHER DETAILS.]
### [Because of this new reasoning behavior, which output is likely generated by which model]
### [Is this reasoning behavior and its definition really different from the existing reasoning behavior above? If not, then you shouldn't include this reasoning behavior in the Added Reasoning Behavior section of your final output.]
...{Repeat for the other new reasoning behaviors}...

Final output:
Updated:
[Original reasoning behavior name] -> [Updated reasoning behavior name]: [Updated detailed reasoning behavior definition] [If this reasoning behavior is observed, which model generated this reasoning output] [Updated example of this behavior quoted from the given outputs; Updated model's actual name if you want to make a reference]

Added:
[Added reasoning behavior name]: [Detailed reasoning behavior definition] [If this reasoning behavior is observed, which model generated this reasoning output] [Example of this behavior quoted from the given outputs; Use the model's actual name if you want to make a reference but do not use OUTPUT A or OUTPUT B]
------

Make sure you follow the exact format above when giving the added reasoning behavior. Write the reasoning behavior name, reasoning behavior definition, model exhibits that reasoning behavior, and example in the same line.

Below is the existing reasoning taxonomy,
"""